version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
